
FROM ubuntu:21.04

ENV DEBIAN_FRONTEND noninteractive

# Install packages
ADD ./provision/ubuntu/provision.ubuntu.sh /provision.ubuntu.sh

ADD ./provision/supervisor/supervisor.conf /etc/supervisor/conf.d/supervisor.conf

RUN chmod +x /*.sh

RUN /provision.ubuntu.sh

WORKDIR /var/www/app

EXPOSE 80 22 35729 9876
CMD ["/usr/bin/supervisord"]